server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://s:123@${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server
  #开启基础权限校验 配合spring-boot-starter-security使用
  security:
    basic:
      enabled: true
    user:
      name: s
      password: 123

